[package]
name = "remodel"
version = "0.7.0"
description = "A tool to read, modify, and write Roblox objects."
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/rojo-rbx/remodel"
documentation = "https://github.com/rojo-rbx/remodel"
repository = "https://github.com/rojo-rbx/remodel"
readme = "README.md"

[features]
default = []

# Enables the unstable Rojo API for Remodel
unstable_rojo_api = ["rojo"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
anyhow = "1.0.27"
backtrace = "0.3.45"
log = "0.4.8"
rbx_binary = "0.4.1"
rbx_dom_weak = "1.10.0"
rbx_reflection = "3.2.399"
rbx_xml = "0.11.2"
reqwest = "0.9.20"
rlua = "0.17.0"
serde = "1.0.104"
serde_json = "1.0.44"
structopt = "0.3.11"

rojo = { git = "https://github.com/rojo-rbx/rojo.git", rev = "build-api", optional = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.6.2"

[dependencies.env_logger]
version = "0.7.1"
default-features = false
features = ["termcolor", "atty"]