[package]
name = "remodel"
version = "0.1.0"
description = "A tool to read, modify, and write Roblox objects."
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbx_dom_weak = "1.9.0"
rbx_xml = "0.11.2"
rlua = "0.16.3"
structopt = "0.3.1"
