[package]
name = "remodel"
version = "0.3.0"
description = "A tool to read, modify, and write Roblox objects."
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/rojo-rbx/remodel"
documentation = "https://github.com/rojo-rbx/remodel"
repository = "https://github.com/rojo-rbx/remodel"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbx_binary = "0.4.1"
log = "0.4.8"
rbx_dom_weak = "1.10.0"
rbx_xml = "0.11.2"
rlua = "0.16.3"
structopt = "0.3.1"

[dependencies.env_logger]
version = "0.6.2"
default-features = false
features = ["termcolor", "atty"]