name: CI

on:
  pull_request:
  push:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, "1.37.0"]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust toolchain
      run: |
        rustup default ${{ matrix.rust_version }}
        rustup component add clippy rustfmt
    - name: Build
      run: cargo build --locked --verbose
    - name: Run tests
      run: |
        cargo test --locked --verbose
        ./bin/test.sh
    - name: Clippy
      run: cargo clippy
    - name: Rustfmt check
      run: cargo fmt -- --check
