name: CI

on:
  pull_request:
  push:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, "1.37.0"]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Rust toolchain
      run: |
        rustup default ${{ matrix.rust_version }}
        rustup component add clippy rustfmt

    - name: Build (default)
      run: cargo build --locked --verbose

    - name: Run tests (default)
      run: |
        cargo test --locked --verbose
        ./bin/test.sh

    - name: Build (default)
      run: cargo build --all-features --locked --verbose

    - name: Run tests (default)
      run: |
        cargo test --all-features --locked --verbose
        ./bin/test.sh --all-features

    - name: Rustfmt and Clippy
      run: |
        cargo fmt -- --check
        cargo clippy
      if: matrix.rust_version == 'stable'
