name: Release

on:
  release:
    types: [created]

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build release binary
      run: cargo build --verbose --locked --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: remodel-win64
        path: target/release/remodel.exe

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Build release binary
      run: |
        echo "Adding Rust to PATH"
        source $HOME/.cargo/env
        echo "Added Rust to PATH, running build..."
        cargo build --verbose --locked --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: remodel-macos
        path: target/release/remodel
